BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `ziskej_packages` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`token`	TEXT NOT NULL UNIQUE,
	`added`	REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS `service` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL UNIQUE,
	`prefix`	TEXT NOT NULL,
	`postfix`	TEXT NOT NULL,
	`submitter_id`	INTEGER NOT NULL,
	`modul`	INTEGER NOT NULL,
	`padding`	INTEGER NOT NULL,
	`offset`	INTEGER NOT NULL
);
COMMIT;
